codecov:
  branch: develop
coverage:
  range: 50...100
  status:
    patch:
      default:
        target: 50
    project:
      default:
        target: auto
        threshold: 0.05
    changes:
      default:
        enabled: no
comment:
  layout: "reach, diff"
flags:
  alltests:
    joined: false
ignore:
  - test/tools/fuzzTesting/fuzzHelper.cpp
  - libskutils/*
