name: clang-format Check
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.10.0
        with:
          clang-format-version: '10'         
          check-path: '.'
          include-regex: '^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu))$'
          exclude-regex: '(CMakeFiles/*|cmake/*|deps/*|build/*|skaled_ssl_test/*|newer_lcov/*|libskutils/src/*)'
